# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/stable/elements.html

- name: article
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
    linkable: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true


- name: slider
  unique: false
  picture_gallery: true
  linkable: true

- name: html
  hint: true
  unique: false
  contents:
  - name: Content
    type: EssenceHtml
    hint: true

- name: background_image
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: background_image_div
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: background_image_plan
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: interactive_tree_columns
  hint: true
  unique: false
  contents:
  - name: headline1
    type: EssenceText
    default: :interactive_tree_columns_headline1
    hint: true
  - name: text1
    type: EssenceRichtext
    default: :interactive_tree_columns_text1
    hint: true
  - name: picture1
    type: EssencePicture
    hint: true
  - name: headline2
    type: EssenceText
    default: :interactive_tree_columns_headline2
    hint: true
  - name: text2
    type: EssenceRichtext
    default: :interactive_tree_columns_article_text2
    hint: true
  - name: picture2
    type: EssencePicture
    hint: true
  - name: headline3
    type: EssenceText
    default: :interactive_tree_columns_headline3
    hint: true
  - name: text3
    type: EssenceRichtext
    default: :interactive_tree_columns_article_text2
    hint: true
  - name: picture3
    type: EssencePicture
    hint: true

- name: interactive_three_columns_text
  hint: true
  unique: false
  contents:
  - name: headline1
    type: EssenceText
    default: :article_headline
    hint: true
  - name: headline2
    type: EssenceText
    default: :article_headline
    hint: true
  - name: headline3
    type: EssenceText
    default: :article_headline
    hint: true

  - name: text1_1
    type: EssenceRichtext
    default: :article_text
    hint: true
  - name: text1_2
    type: EssenceRichtext
    default: :article_text
    hint: true
  - name: footer1
    type: EssenceText
    default: :article_headline
    hint: true

  - name: text2_1
    type: EssenceRichtext
    default: :article_text
    hint: true
  - name: text2_2
    type: EssenceRichtext
    default: :article_text
    hint: true
  - name: footer2
    type: EssenceText
    default: :article_headline
    hint: true

  - name: text3_1
    type: EssenceRichtext
    default: :article_text
    hint: true
  - name: text3_2
    type: EssenceRichtext
    default: :article_text
    hint: true
  - name: footer3
    type: EssenceText
    default: :article_headline
    hint: true

- name: cite
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: headline2
    type: EssenceText
    default: :article_headline
    hint: true

- name: pages_header
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true

- name: testimonials_items
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: article_image_move
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
    linkable: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: text_glitch
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
    linkable: true

- name: image_parallax
  hint: true
  unique: false
  contents:
  - name: headline
    type: EssenceText
    default: :article_headline
    hint: true
  - name: picture
    type: EssencePicture
    hint: true
    linkable: true
  - name: text
    type: EssenceRichtext
    default: :article_text
    hint: true

- name: contactform
  contents:
  - name: mail_from
    type: EssenceText
    validate:
    - presence
    - format: email
  - name: mail_to
    type: EssenceText
    validate:
    - presence
    - format: email
  - name: subject
    type: EssenceText
    validate:
    - presence
  - name: success_page
    type: EssenceSelect
    validate:
    - presence

