# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html


- name: standard
  unique: false
  elements: [article,slider,html,product_category,product, interactive_tree_columns, interactive_three_columns_text, cite,
  pages_header, testimonials_items, article_image_move,text_glitch, image_parallax]

- name: container
  unique: false
  elements: [article,slider,html,product_category,product, interactive_tree_columns, interactive_three_columns_text, cite,
  pages_header, testimonials_items, article_image_move,text_glitch, image_parallax]

- name: contact
  unique: true
  cache: false
  elements: [pageheading, heading, contactform]
  autogenerate: [contactform]



