# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html


- name: standard
  unique: false
  elements: [article,slider,html,product_category,product,background_image,background_image_div, background_image_plan]

- name: container
  unique: false
  elements: [article,slider,html,product_category,product,background_image,background_image_div, background_image_plan ]



