

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 
  access_key_id: ENV['AWS_ACCESS_KEY_ID']
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']